# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
