# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
